.TH "include/App.hpp" 3 "Wed Aug 20 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/App.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <CLI/CLI\&.hpp>\fP
.br
\fC#include 'Window\&.hpp'\fP
.br
\fC#include 'Directory\&.hpp'\fP
.br
\fC#include 'Types\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBintfl::App\fP"
.br
.RI "Singleton class represents console Application\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINTFL_INIT_APP_HPP_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INTFL_INIT_APP_HPP_"

.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
