.TH "include/Colors.hpp" 3 "Sat Aug 16 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Colors.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <array>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBintfl::NcursesColors\fP"
.br
.RI "class encapsulating ncurses colors specific methods & data "
.ti -1c
.RI "class \fBintfl::NcursesColors::Color\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINTFL_COLOR_HPP\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBCOLOR_BLACK\fP, \fBCOLOR_YELLOW\fP, \fBCOLOR_RED\fP, \fBCOLOR_WHITE\fP, \fBCOLOR_BLUE\fP, \fBCOLOR_GREEN\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INTFL_COLOR_HPP"

.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICOLOR_BLACK \fP\fP
.TP
\fB\fICOLOR_YELLOW \fP\fP
.TP
\fB\fICOLOR_RED \fP\fP
.TP
\fB\fICOLOR_WHITE \fP\fP
.TP
\fB\fICOLOR_BLUE \fP\fP
.TP
\fB\fICOLOR_GREEN \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
