.TH "src/Colors.cpp" 3 "Wed Aug 20 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Colors.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Colors\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBCOLOR_BLACK\fP, \fBCOLOR_YELLOW\fP, \fBCOLOR_RED\fP, \fBCOLOR_WHITE\fP, \fBCOLOR_BLUE\fP, \fBCOLOR_GREEN\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICOLOR_BLACK \fP\fP
.TP
\fB\fICOLOR_YELLOW \fP\fP
.TP
\fB\fICOLOR_RED \fP\fP
.TP
\fB\fICOLOR_WHITE \fP\fP
.TP
\fB\fICOLOR_BLUE \fP\fP
.TP
\fB\fICOLOR_GREEN \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
