.TH "src/Commands.cpp" 3 "Wed Aug 20 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Commands.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Commands\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBintfl::redraw\fP (const Window &win, const std::vector< FilePrintRepr > &reprs)"
.br
.RI "used to redraw calls "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
