.TH "include/Directory.hpp" 3 "Sat Aug 16 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Directory.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <filesystem>\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'File\&.hpp'\fP
.br
\fC#include 'Window\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBintfl::Directory\fP"
.br
.RI "Contains same data as \fBFile\fP class and additional directory specific one\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINTFL_DIRECTORY_HPP_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INTFL_DIRECTORY_HPP_"

.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
