.TH "src/File.cpp" 3 "Sat Aug 16 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/File.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'File\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
