.TH "include/FileReprPrinter.hpp" 3 "Sat Aug 16 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/FileReprPrinter.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'File\&.hpp'\fP
.br
\fC#include 'Window\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINTFL_FILE_REPR_PRINTER_HPP_\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBintfl::printFileRepr\fP (const FilePrintRepr &file_repr, const Window &win)"
.br
.RI "function to print the \fBFilePrintRepr\fP to a specified window "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INTFL_FILE_REPR_PRINTER_HPP_"

.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
