.TH "include/File.hpp" 3 "Tue Aug 19 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/File.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <filesystem>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Types\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBintfl::FilePrintRepr\fP"
.br
.RI "print-ready representation of file "
.ti -1c
.RI "class \fBintfl::File\fP"
.br
.RI "Contains an information about file such as filename, path, metadata\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINTFL_FILE_HPP_\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBintfl::FilePtr\fP = std::unique_ptr< File >"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INTFL_FILE_HPP_"

.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
