.TH "include/HandleInput.hpp" 3 "Tue Aug 19 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/HandleInput.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'App\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINTFL_HANDLE_INPUT_HPP_\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBintfl::getCommand\fP (App &app, std::vector< FilePrintRepr > &A_reprs, std::wstring &A_command)"
.br
.RI "Proccess input, yield the command string and handle some other events\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INTFL_HANDLE_INPUT_HPP_"

.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
