.TH "src/HandleInput.cpp" 3 "Tue Aug 19 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/HandleInput.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'HandleInput\&.hpp'\fP
.br
\fC#include <string>\fP
.br
\fC#include <cwchar>\fP
.br
\fC#include <cwctype>\fP
.br
\fC#include 'Colors\&.hpp'\fP
.br
\fC#include 'File\&.hpp'\fP
.br
\fC#include 'Commands\&.hpp'\fP
.br
\fC#include 'Types\&.hpp'\fP
.br
\fC#include 'App\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBintfl::getCommand\fP (App &app, std::vector< FilePrintRepr > &A_reprs, std::wstring &A_command)"
.br
.RI "Proccess input, yield the command string and handle some other events\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
