.TH "intfl::FSDirectoryParser" 3 "Mon Aug 18 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
intfl::FSDirectoryParser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parser\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBparse\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, std::wstring > \fBM_parser_flags\fP"
.br
.ti -1c
.RI "\fBDirectory\fP \fBM_dir\fP = \fBDirectory\fP('\&.')"
.br
.ti -1c
.RI "\fBFilters\fP \fBM_filters\fP"
.br
.ti -1c
.RI "\fBSortPriories\fP \fBM_sort_priorities\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void intfl::FSDirectoryParser::parse ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBDirectory\fP intfl::FSDirectoryParser::M_dir = \fBDirectory\fP('\&.')"

.SS "\fBFilters\fP intfl::FSDirectoryParser::M_filters"

.SS "std::map<std::string, std::wstring> intfl::FSDirectoryParser::M_parser_flags"

.SS "\fBSortPriories\fP intfl::FSDirectoryParser::M_sort_priorities"


.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
