.TH "intfl::FilePrintRepr" 3 "Tue Aug 19 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
intfl::FilePrintRepr \- print-ready representation of file  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <File\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilePrintRepr\fP (const \fBNestingMap\fP &nesting_map, const \fBFile\fP *\fBfile\fP=nullptr, size_t n_rest_elements=0)"
.br
.ti -1c
.RI "const \fBFile\fP *const \fBfile\fP () const"
.br
.ti -1c
.RI "size_t \fBgetRest\fP () const"
.br
.ti -1c
.RI "const \fBNestingMap\fP & \fBnesting\fP () const"
.br
.ti -1c
.RI "std::wstring \fBtoWstr\fP () const"
.br
.ti -1c
.RI "\fB~FilePrintRepr\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
print-ready representation of file 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "intfl::FilePrintRepr::FilePrintRepr (const \fBNestingMap\fP & nesting_map, const \fBFile\fP * file = \fCnullptr\fP, size_t n_rest_elements = \fC0\fP)\fC [inline]\fP"

.SS "intfl::FilePrintRepr::~FilePrintRepr ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBFile\fP *const intfl::FilePrintRepr::file () const\fC [inline]\fP"

.SS "size_t intfl::FilePrintRepr::getRest () const\fC [inline]\fP"

.SS "const \fBNestingMap\fP & intfl::FilePrintRepr::nesting () const\fC [inline]\fP"

.SS "std::wstring intfl::FilePrintRepr::toWstr () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
