.TH "intfl::NcursesColors::Color" 3 "Sat Aug 16 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
intfl::NcursesColors::Color
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Colors\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBon\fP () const"
.br
.ti -1c
.RI "void \fBoff\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBNcursesColors\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void intfl::NcursesColors::Color::off () const\fC [inline]\fP"

.SS "void intfl::NcursesColors::Color::on () const\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBNcursesColors\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
