.TH "intfl::Flags" 3 "Wed Aug 20 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
intfl::Flags
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Types\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBall\fP {false}"
.br
.ti -1c
.RI "bool \fBdirs_only\fP {false}"
.br
.ti -1c
.RI "bool \fBprune\fP {false}"
.br
.ti -1c
.RI "bool \fBfull_filenames\fP {false}"
.br
.ti -1c
.RI "bool \fBuser\fP {false}"
.br
.ti -1c
.RI "bool \fBgroup\fP {false}"
.br
.ti -1c
.RI "bool \fBsize\fP {false}"
.br
.ti -1c
.RI "bool \fBdisk_usage\fP {false}"
.br
.ti -1c
.RI "bool \fBno_colors\fP {false}"
.br
.ti -1c
.RI "bool \fBascii\fP {false}"
.br
.ti -1c
.RI "bool \fBhelp\fP {false}"
.br
.ti -1c
.RI "size_t \fBprint_max_depth\fP = 5"
.br
.ti -1c
.RI "size_t \fBfiles_limit\fP = 15"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool intfl::Flags::all {false}"

.SS "bool intfl::Flags::ascii {false}"

.SS "bool intfl::Flags::dirs_only {false}"

.SS "bool intfl::Flags::disk_usage {false}"

.SS "size_t intfl::Flags::files_limit = 15"

.SS "bool intfl::Flags::full_filenames {false}"

.SS "bool intfl::Flags::group {false}"

.SS "bool intfl::Flags::help {false}"

.SS "bool intfl::Flags::no_colors {false}"

.SS "size_t intfl::Flags::print_max_depth = 5"

.SS "bool intfl::Flags::prune {false}"

.SS "bool intfl::Flags::size {false}"

.SS "bool intfl::Flags::user {false}"


.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
