.TH "intfl::NcursesColors::Color" 3 "Wed Aug 20 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
intfl::NcursesColors::Color \- represents NcursesColor pair  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Colors\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "short \fBgetId\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBNcursesColors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
represents NcursesColor pair 
.SH "Member Function Documentation"
.PP 
.SS "short intfl::NcursesColors::Color::getId () const\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBNcursesColors\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
