.TH "include/MainLoop.hpp" 3 "Sat Aug 16 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/MainLoop.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Directory\&.hpp'\fP
.br
\fC#include 'Window\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINTFL_MAIN_LOOP_HPP_\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBintfl::mainLoop\fP (const Directory &dir, Window &mainWin, Window &cmdsWin, int argc, char *argv[])"
.br
.RI "function for managing app's main loop "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INTFL_MAIN_LOOP_HPP_"

.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
