.TH "include/Types.hpp" 3 "Tue Aug 19 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Types.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <filesystem>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBintfl::NestingMap\fP"
.br
.RI "represents file's nesting hierarchy "
.ti -1c
.RI "struct \fBintfl::Flags\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINTFL_TYPES_HPP_\fP"
.br
.ti -1c
.RI "#define \fBNESTING_EMPTY\fP   L'    '"
.br
.ti -1c
.RI "#define \fBNESTING_VLINE\fP   L'|   '"
.br
.ti -1c
.RI "#define \fBNESTING_BRANCH_CONTINUE\fP   L'|\-\- '"
.br
.ti -1c
.RI "#define \fBNESTING_BRANCH_LAST\fP   L'|__ '"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INTFL_TYPES_HPP_"

.SS "#define NESTING_BRANCH_CONTINUE   L'|\-\- '"

.SS "#define NESTING_BRANCH_LAST   L'|__ '"

.SS "#define NESTING_EMPTY   L'    '"

.SS "#define NESTING_VLINE   L'|   '"

.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
