.TH "include/Window.hpp" 3 "Sat Aug 16 2025" "intfl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Window.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Colors\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBintfl::Window\fP"
.br
.RI "class encapsulates behaviour related to specific area of the screen\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBintfl\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINTFL_WINDOW_HPP_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INTFL_WINDOW_HPP_"

.SH "Author"
.PP 
Generated automatically by Doxygen for intfl from the source code\&.
